package no.bankid.outgoing.ra;

import io.swagger.v3.oas.annotations.media.Schema;

import static io.swagger.v3.oas.annotations.media.Schema.RequiredMode.NOT_REQUIRED;
import static io.swagger.v3.oas.annotations.media.Schema.RequiredMode.REQUIRED;

@Schema(description = "Response from identity verification check. Note: Verification codes are single-attempt - if the code is invalid, a new code must be generated by the RA officer.")
public class CheckUserIdentityVerificationResponseDTO {

    public enum ErrorCode {
        INVALID,
        EXPIRED,
        CONSUMED
    }

    @Schema(
            description = "Whether the verification code was valid and successfully consumed",
            requiredMode = REQUIRED
    )
    public boolean verified;

    @Schema(
            description = "Error code if verification failed. Possible values: INVALID (verification code does not match, a new code must be generated), EXPIRED (verification code has expired, codes expire after 5 minutes), CONSUMED (verification code has already been used)",
            requiredMode = NOT_REQUIRED
    )
    public ErrorCode error;
}
